[project]
name = "hemzeni"
version = "0.1.0"
description = "hemzeni"
requires-python = ">=3.10,<3.11"
authors = [{ name = "Your Name", email = "you@example.com" }]
license = { text = "MIT" }
readme = "README.md"

dependencies = [
    # "python (>=3.10,<3.11)",
    # "marimo (>=0.13.6,<0.14.0)",
    "streamlit (>=1.45.0,<2.0.0)",
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    # "mediapipe (>=0.10.21,<0.11.0)",
    "aipose (>=3.1.0,<4.0.0)",
    "torch (>=2.5.1,<2.6.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "flask (>=3.1.1,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.9"
pytest = "^8.3.5"
